
management:
  info:
    git:
      mode: full
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

security:
  basic:
    enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/erueka

message:  hello NYC
